version: '3'
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./next:/next
    working_dir: /next
    command: node
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000