/// <reference types="react" />
/**
 * Embeds an AMP Script by either linking to a JS `src` file or embedding inline
 * AMP Script via the `script` property. The inline script hash will automatically
 * be generated by AMP Optimizer.
 *
 * @param {Props} props
 */
export declare function AmpScript(props: any): JSX.Element;
