"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = __importDefault(require("react"));
/**
 * Embeds an AMP Script by either linking to a JS `src` file or embedding inline
 * AMP Script via the `script` property. The inline script hash will automatically
 * be generated by AMP Optimizer.
 *
 * @param {Props} props
 */
function AmpScript(props) {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement(AmpScriptTag, Object.assign({}, props)),
        props.script && (react_1.default.createElement("script", { id: props.id, type: "text/plain", 
            // @ts-ignore
            target: "amp-script", dangerouslySetInnerHTML: {
                __html: generateInlineScript(props.script),
            } }))));
}
exports.AmpScript = AmpScript;
function AmpScriptTag(props) {
    return (
    // @ts-ignore
    react_1.default.createElement("amp-script", Object.assign({}, props)));
}
function generateInlineScript(script) {
    if (typeof script === "function") {
        return `${script.toString()}()`;
    }
    return String(script);
}
